language: generic
sudo: required
services:
  - docker

before_install:
    - docker build -t denisicun/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true denisicun/react-test npm run test -- --coverage

after_success:
    - docker build -t denisicun/multi-client ./client
    - docker build -t denisicun/multi-nginx ./nginx
    - docker build -t denisicun/multi-server ./server
    - docker build -t denisicun/multi-worker ./worker
    # Log in to dockerhub from travis ci
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to dockerhub
    - docker push denisicun/multi-client
    - docker push denisicun/multi-nginx
    - docker push denisicun/multi-server
    - docker push denisicun/multi-worker
